apiRules:
# ✅ Allow only namespaces that start by AshesOfVelsingrad
- include:
    uidRegex: ^AshesOfVelsingrad(\..*)?$
    type: Namespace

# ⛔ Exclude useless namespaces
- exclude:
    uidRegex: ^gdUnit4(\..*)?$
    type: Namespace
- exclude:
    uidRegex: ^Tests(\..*)?$
    type: Namespace

# ⛔ Exclude specific types
- exclude:
    uidRegex: ^*.PropertyName.*$
- exclude:
    uidRegex: ^*.MethodName.*$
- exclude:
    uidRegex: ^*.SignalName.*$
- exclude:
    type: Delegate
