name: Mirror to School Repository

on:
  push:
    branches:
      - release
      - canary
      - develop

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Push to school repository
        env:
          SCHOOL_REPO_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote add epitech https://x-access-token:${SCHOOL_REPO_TOKEN}@github.com/EpitechPGE45-2025/G-EIP-700-PAR-7-1-eip-99.git
          git push epitech release canary develop
